dictionaries:
  - en

excluded_files:
  - 'src/**/*'
  - 'config/**/*'
  - 'yarn.lock'
  - '.typo-ci.yml'

excluded_words:
  - prefixParseFns
  - nuds
  - leds
  - infixParseFns
  - lexing
  - Thorsten
  - Yay
  - Reddit
  - tokenize
  - mins
  - unfollow
  - Anki
  - Kendi
  - Ibram

