name: Audit pull request
on:
  status
jobs:
  audit:
    runs-on: ubuntu-latest
    if: github.event.context == 'netlify/deploy-preview' && github.event.state == 'success'
    steps:
      - name: Audit Netlify deploy preview
        uses: jakejarvis/lighthouse-action@master
        with:
          netlify_site: 'keen-roentgen-cafcb7.netlify.com'
          url: 'https://deploy-preview-[[PR_NUMBER]]--[[NETLIFY_SITE]].netlify.com'
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
