name: Install and Build with Node
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: yarn build
        env:
          CI: true

- name: Check Spelling (JS, Vue, HTML, Markdown, Text)
  uses: UnicornGlobal/spellcheck-github-actions@0.4.0
